import java.awt.event.ActionEvent;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.DecimalFormat;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.event.ChangeEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author Megan
 */
public class GripApp extends javax.swing.JApplet {

	private String[] gripList = { "contracture" };

	private GripFab gripFab = new GripFab();
	private int gripsMadeInSession = 0;
	private DecimalFormat df = new DecimalFormat("###.##");

	private String hole = "Circle";
	private String barrel = "None";

	/**
	 * Initializes the applet GripApp
	 */
	@Override
	public void init() {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */

		resize(675, 600);
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GripApp.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GripApp.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GripApp.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GripApp.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the applet */
		try {
			java.awt.EventQueue.invokeAndWait(new Runnable() {
				public void run() {
					initComponents();
				}
			});
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}

	/**
	 * This method is called from within the init() method to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		Panel = new javax.swing.JTabbedPane();
		directory = new javax.swing.JPanel();
		directoryChooser = new javax.swing.JFileChooser();
		jLabel76 = new javax.swing.JLabel();
		grips = new javax.swing.JPanel();
		gripBox = new javax.swing.JComboBox();
		chooseGrip = new javax.swing.JButton();
		jLabel29 = new javax.swing.JLabel();
		profileChooser = new javax.swing.JFileChooser();
		newCheck = new javax.swing.JRadioButton();
		profileCheck = new javax.swing.JRadioButton();
		holeSettings = new javax.swing.JPanel();
		jLabel74 = new javax.swing.JLabel();
		holeChoices = new javax.swing.JComboBox();
		diameterLabel = new javax.swing.JLabel();
		diameterSlider = new javax.swing.JSlider();
		jLabel82 = new javax.swing.JLabel();
		heightSlider = new javax.swing.JSlider();
		jLabel83 = new javax.swing.JLabel();
		widthSlider = new javax.swing.JSlider();
		jLabel84 = new javax.swing.JLabel();
		jLabel85 = new javax.swing.JLabel();
		jLabel86 = new javax.swing.JLabel();
		diameter = new javax.swing.JTextField(3);
		height = new javax.swing.JTextField(3);
		width = new javax.swing.JTextField(3);
		jLabel87 = new javax.swing.JLabel();
		jLabel88 = new javax.swing.JLabel();
		jLabel89 = new javax.swing.JLabel();
		submitHole = new javax.swing.JButton();
		holeDescription = new javax.swing.JLabel();
		barrelSettings = new javax.swing.JPanel();
		jLabel75 = new javax.swing.JLabel();
		barrelChoices = new javax.swing.JComboBox();
		jLabel900 = new javax.swing.JLabel();
		loutSlider = new javax.swing.JSlider();
		jLabel90 = new javax.swing.JLabel();
		linSlider = new javax.swing.JSlider();
		jLabel91 = new javax.swing.JLabel();
		angleSlider = new javax.swing.JSlider();
		jLabel92 = new javax.swing.JLabel();
		jLabel93 = new javax.swing.JLabel();
		jLabel94 = new javax.swing.JLabel();
		lout = new javax.swing.JTextField(3);
		lin = new javax.swing.JTextField(3);
		angle = new javax.swing.JTextField(3);
		jLabel95 = new javax.swing.JLabel();
		jLabel96 = new javax.swing.JLabel();
		jLabel97 = new javax.swing.JLabel();
		submitBarrel = new javax.swing.JButton();
		barrelDescription = new javax.swing.JLabel();
		finish = new javax.swing.JPanel();
		jLabel77 = new javax.swing.JLabel();
		selectProfile = new javax.swing.JCheckBox();
		selectSCAD = new javax.swing.JCheckBox();
		selectSTL = new javax.swing.JCheckBox();
		submitFinish = new javax.swing.JButton();
		jLabel78 = new javax.swing.JLabel();
		jLabel79 = new javax.swing.JLabel();
		jLabel80 = new javax.swing.JLabel();
		gripName = new javax.swing.JTextField();
		jLabel81 = new javax.swing.JLabel();
		lefty = new javax.swing.JCheckBox();

		Panel.setPreferredSize(new java.awt.Dimension(900, 900));
		directory();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(Panel,
								javax.swing.GroupLayout.PREFERRED_SIZE, 676,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(Panel,
								javax.swing.GroupLayout.PREFERRED_SIZE, 539,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
	}// </editor-fold>

	protected void directoryChooserActionPerformed(ActionEvent evt)
			throws IOException {
		int result = directoryChooser.showSaveDialog(this);
		if (result == JFileChooser.APPROVE_OPTION) {
			gripFab.directory = directoryChooser.getSelectedFile()
					.getAbsolutePath();
			gripFab.name = gripFab.directory.substring(gripFab.directory
					.lastIndexOf("\\") + 1);
			Path source = Paths
					.get("C:\\Program Files (x86)\\GripFab\\openScad\\export.bat");
			Path dir = Paths.get(gripFab.directory);
			Path delete = Paths.get(gripFab.directory + "\\export.bat");
			Files.deleteIfExists(delete);
			Files.copy(source, dir.resolve(source.getFileName()));
			source = Paths
					.get("C:\\Program Files (x86)\\GripFab\\openScad\\openscad.exe");
			delete = Paths.get(gripFab.directory + "\\openscad.exe");
			Files.deleteIfExists(delete);
			Files.copy(source, dir.resolve(source.getFileName()));
			grips();
		}
	}

	protected void profileCheckActionPerformed(ActionEvent evt) {
		if (profileCheck.isSelected()) {
			profileChooser.setVisible(true);
			chooseGrip.setVisible(false);
		}
	}

	protected void profileChooserActionPerformed(ActionEvent evt)
			throws GripNotFoundException {
		int result = profileChooser.showSaveDialog(this);
		if (result == JFileChooser.APPROVE_OPTION)
			try {
				chooseGripActionPerformed(evt);
			} catch (IOException e) {
				showStatus("IOException");
				e.printStackTrace();
			}
	}

	protected void newCheckActionPerformed(ActionEvent evt) {
		if (newCheck.isSelected()) {
			profileChooser.setVisible(false);
			chooseGrip.setVisible(true);
		}
	}

	protected void chooseGripActionPerformed(ActionEvent evt)
			throws GripNotFoundException, IOException {
		if (newCheck.isSelected()) {
			if ((gripBox.getSelectedItem() + ".stl").equals("contracture.stl")) {
				Path source = Paths
						.get("C:\\Program Files (x86)\\GripFab\\ContractureGrip\\contractureA.stl");
				Path dir = Paths.get(gripFab.directory);
				Path delete = Paths.get(gripFab.directory
						+ "\\contractureA.stl");
				Files.deleteIfExists(delete);
				Files.copy(source, dir.resolve(source.getFileName()));
				source = Paths
						.get("C:\\Program Files (x86)\\GripFab\\ContractureGrip\\contractureB.stl");
				delete = Paths.get(gripFab.directory + "\\contractureB.stl");
				Files.deleteIfExists(delete);
				Files.copy(source, dir.resolve(source.getFileName()));
				holes();
				showStatus("contrature selected");
			} else
				throw new GripNotFoundException();
		} else if (profileCheck.isSelected()) {
			try {
				gripFab.readProfile(profileChooser.getSelectedFile());
				holes();
				showStatus("profile selected");
			} catch (NumberFormatException e) {
				showStatus("NumberFormatException, contact developer.");
				e.printStackTrace();
			} catch (IOException e) {
				showStatus("IOException, file not located");
				e.printStackTrace();
			}
		} else
			showStatus("please select an option.");
	}

	protected void holeChoicesActionPerformed(ActionEvent evt) {
		setHole((String) holeChoices.getSelectedItem());
	}

	protected void diameterSliderStateChanged(ChangeEvent evt) {
		diameter.setText(df.format((diameterSlider.getValue() * 11.0) / 1000));
	}

	protected void heightSliderStateChanged(ChangeEvent evt) {
		height.setText(df.format((heightSlider.getValue() * 13.0) / 1000));
	}

	protected void widthSliderStateChanged(ChangeEvent evt) {
		width.setText(df.format((widthSlider.getValue() * 13.0) / 1000));
	}

	protected void barrelChoicesActionPerformed(ActionEvent evt) {
		setBarrel((String) barrelChoices.getSelectedItem());
	}

	protected void loutSliderStateChanged(ChangeEvent evt) {
		lout.setText(df.format((loutSlider.getValue() * 200.0) / 1000));
	}

	protected void linSliderStateChanged(ChangeEvent evt) {
		lin.setText(df.format((linSlider.getValue() * 70.0) / 1000));
	}

	protected void angleSliderStateChanged(ChangeEvent evt) {
		angle.setText(df.format((angleSlider.getValue() * 90.0) / 1000));
	}

	protected void submitFinishActionPerformed(ActionEvent evt)
			throws PositionNotSupportedException, invalidDiameterException,
			STLNotPresentException, invalidDimmensionsException, IOException,
			InterruptedException {
		gripFab.name = gripName.getText();
		gripFab.lefty = lefty.isSelected();
		gripFab.hole = hole;
		gripFab.barrel = barrel;
		if (selectProfile.isSelected())
			gripFab.writeProfile();
		if (selectSCAD.isSelected())
			gripFab.writefile();
		if (selectSTL.isSelected())
			gripFab.writeSTL();
		if (selectProfile.isSelected() || selectSCAD.isSelected()) {
			gripsMadeInSession++;
			if (Character.isDigit(gripName.getText().charAt(
					gripName.getText().length() - 1)))
				gripName.setText(gripName.getText().substring(0,
						gripName.getText().length() - 1)
						+ gripsMadeInSession);
			else
				gripName.setText(gripName.getText() + gripsMadeInSession);
		}
		showStatus("Files are Submitted: Please check your selected directory.");
	}

	protected void selectSCADActionPerformed(ActionEvent evt) {
		if (selectSCAD.isSelected())
			selectSTL.setVisible(true);
		else {
			selectSTL.setVisible(false);
			selectSTL.setSelected(false);
		}
	}

	private void diameterActionPerformed(java.awt.event.ActionEvent evt) {
		double text = Double.parseDouble(diameter.getText());
		diameterSlider.setValue((int) (text * 1000 / 11));
	}

	private void heightActionPerformed(java.awt.event.ActionEvent evt) {
		double text = Double.parseDouble(height.getText());
		heightSlider.setValue((int) (text * 1000 / 13));
	}

	private void widthActionPerformed(java.awt.event.ActionEvent evt) {
		double text = Double.parseDouble(width.getText());
		widthSlider.setValue((int) (text * 1000 / 13));
	}

	private void submitHoleActionPerformed(java.awt.event.ActionEvent evt) {
		hole = (String) holeChoices.getSelectedItem();
		gripFab.diameter = Double.parseDouble(diameter.getText());
		gripFab.height = Double.parseDouble(height.getText());
		gripFab.width = Double.parseDouble(width.getText());
		barrels();
	}

	private void loutActionPerformed(java.awt.event.ActionEvent evt) {
		double text = Double.parseDouble(lout.getText());
		loutSlider.setValue((int) (text * 1000 / 200));
	}

	private void linActionPerformed(java.awt.event.ActionEvent evt) {
		double text = Double.parseDouble(lin.getText());
		linSlider.setValue((int) (text * 1000 / 70));
	}

	private void angleActionPerformed(java.awt.event.ActionEvent evt) {
		double text = Double.parseDouble(angle.getText());
		angleSlider.setValue((int) (text * 1000 / 90));
	}

	private void submitBarrelActionPerformed(java.awt.event.ActionEvent evt) {
		barrel = (String) barrelChoices.getSelectedItem();
		gripFab.lin = Double.parseDouble(lin.getText());
		gripFab.lout = Double.parseDouble(lout.getText());
		gripFab.angle = Double.parseDouble(angle.getText());
		finish();
	}

	private void setHole(String h) {
		if (h.equals(gripFab.holeList[0])) {
			holeDescription
					.setText("Creates a circular hole for the item to slide into. Good for pens.");
			diameterSlider.setEnabled(true);
			diameter.setEditable(true);
			heightSlider.setEnabled(false);
			heightSlider.setValue(0);
			height.setEditable(false);
			height.setText("" + 0.00);
			widthSlider.setEnabled(false);
			widthSlider.setValue(0);
			width.setEditable(false);
			width.setText("" + 0);
		} else if (h.equals(gripFab.holeList[1])) {
			holeDescription
					.setText("Creates a rectangular hole for the item to slide into.");
			diameterSlider.setEnabled(false);
			diameterSlider.setValue(0);
			diameter.setEditable(false);
			diameter.setText("" + 0);
			heightSlider.setEnabled(true);
			height.setEditable(true);
			widthSlider.setEnabled(true);
			width.setEditable(true);
		}
	}

	private void setBarrel(String b) {
		if (b.equals(gripFab.barrelList[0])) {
			barrelDescription
					.setText("Creates a simple grip with a hole for items to slide into.");
			linSlider.setEnabled(true);
			lin.setEditable(true);
			loutSlider.setEnabled(false);
			loutSlider.setValue(0);
			lout.setEditable(false);
			lout.setText("" + 0);
			angleSlider.setEnabled(false);
			angleSlider.setValue(0);
			angle.setEditable(false);
			angle.setText("" + 0);
		} else if (b.equals(gripFab.barrelList[1])) {// straight
			barrelDescription
					.setText("Creates an straight barrel. Adds support to longer items. Great for writing.");
			linSlider.setEnabled(true);
			lin.setEditable(true);
			loutSlider.setEnabled(true);
			lout.setEditable(true);
			angleSlider.setEnabled(false);
			angleSlider.setValue(0);
			angle.setEditable(true);
			angle.setText("" + 0);
		} else if (b.equals(gripFab.barrelList[2])) {// angled
			barrelDescription
					.setText("Creates an angled barrel. Adds support to the item and points it at and angle.");
			linSlider.setEnabled(false);
			linSlider.setValue(0);
			lin.setEditable(false);
			lin.setText("" + 0);
			loutSlider.setEnabled(true);
			lout.setEditable(true);
			angleSlider.setEnabled(true);
			angle.setEditable(true);
		}
	}

	private void directory() {
		directoryChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		directoryChooser.setAcceptAllFileFilterUsed(false);

		directoryChooser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					directoryChooserActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		directoryChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

		jLabel76.setText("Choose Directory:");

		setLayouts();

		Panel.addTab("Choose Directory", directory);
		Panel.setSelectedIndex(Panel.indexOfTab("Choose Directory"));
	}

	private void grips() {
		gripBox.setModel(new DefaultComboBoxModel(gripList));
		chooseGrip.setText("Choose");
		chooseGrip.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					chooseGripActionPerformed(evt);
				} catch (GripNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel29.setText("or");

		profileChooser.setVisible(false);
		profileChooser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					profileChooserActionPerformed(evt);
				} catch (GripNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		buttonGroup1.add(newCheck);
		newCheck.setSelected(true);
		newCheck.setText("New Grip");
		newCheck.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				newCheckActionPerformed(evt);
			}
		});

		buttonGroup1.add(profileCheck);
		profileCheck.setText("Grip From Profile:");
		profileCheck.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				profileCheckActionPerformed(evt);
			}
		});

		setLayouts();
		Panel.addTab("Grips", grips);
		Panel.setSelectedIndex(Panel.indexOfTab("Grips"));
	}

	private void holes() {
		jLabel74.setText("How would you like the hole shaped?");

		holeChoices.setModel(new DefaultComboBoxModel(gripFab.holeList));
		holeChoices.setSelectedItem(hole);
		holeChoices.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				holeChoicesActionPerformed(evt);
			}
		});
		diameterLabel.setText("Diameter:");
		diameter.setText("" + gripFab.diameter);
		diameter.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				diameterActionPerformed(evt);
			}
		});

		height.setText("" + gripFab.height);
		height.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				heightActionPerformed(evt);
			}
		});

		width.setText("" + gripFab.width);
		width.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				widthActionPerformed(evt);
			}
		});

		diameterSlider.setMaximum(1000);
		double text = Double.parseDouble(diameter.getText());
		diameterSlider.setValue((int) (text * 1000 / 11));
		diameterSlider
				.addChangeListener(new javax.swing.event.ChangeListener() {
					public void stateChanged(javax.swing.event.ChangeEvent evt) {
						diameterSliderStateChanged(evt);
					}
				});

		jLabel82.setText("The diameter of your circle should fit tightly around your object.");

		heightSlider.setMaximum(1000);
		text = Double.parseDouble(height.getText());
		heightSlider.setValue((int) (text * 1000 / 13));
		heightSlider.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				heightSliderStateChanged(evt);
			}
		});

		jLabel83.setText("The height of your rectangle should fit tightly around your object.");

		widthSlider.setMaximum(1000);
		text = Double.parseDouble(width.getText());
		widthSlider.setValue((int) (text * 1000 / 13));
		widthSlider.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				widthSliderStateChanged(evt);
			}
		});

		jLabel84.setText("The width of your rectangle should fit tightly around your object.");

		jLabel85.setText("Height:");

		jLabel86.setText("Width:");

		jLabel87.setText("mm");

		jLabel88.setText("mm");

		jLabel89.setText("mm");

		submitHole.setText("Submit Hole");
		submitHole.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				submitHoleActionPerformed(evt);
			}
		});

		holeDescription
				.setText("Creates a circular hole for the item to slide into. Good for pens.");
		setHole(hole);
		Panel.remove(barrelSettings);
		Panel.remove(finish);
		Panel.addTab("Hole Settings", holeSettings);
		Panel.setSelectedIndex(Panel.indexOfTab("Hole Settings"));
	}

	private void barrels() {
		jLabel75.setText("What kind of barrel would you like?");

		barrelChoices.setModel(new DefaultComboBoxModel(gripFab.barrelList));
		barrelChoices.setSelectedItem(barrel);
		barrelChoices.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				barrelChoicesActionPerformed(evt);
			}
		});
		jLabel900.setText("Grip Depth:");

		lout.setText("" + gripFab.lout);
		lout.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loutActionPerformed(evt);
			}
		});

		lin.setText("" + gripFab.lin);
		lin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				linActionPerformed(evt);
			}
		});

		angle.setText("" + gripFab.angle);
		angle.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				angleActionPerformed(evt);
			}
		});

		loutSlider.setMaximum(1000);
		double text = Double.parseDouble(lout.getText());
		loutSlider.setValue((int) (text * 1000 / 200));
		loutSlider.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				loutSliderStateChanged(evt);
			}
		});

		jLabel90.setText("The diameter of your circle should fit tightly around your object.");

		linSlider.setMaximum(1000);
		text = Double.parseDouble(lin.getText());
		linSlider.setValue((int) (text * 1000 / 70));
		linSlider.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				linSliderStateChanged(evt);
			}
		});

		jLabel91.setText("The barrel length should run the length of the item it is supporting. ");

		angleSlider.setMaximum(1000);
		text = Double.parseDouble(angle.getText());
		angleSlider.setValue((int) (text * 1000 / 90));
		angleSlider.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				angleSliderStateChanged(evt);
			}
		});

		jLabel92.setText("The angle at which you want the barrel to point");

		jLabel93.setText("Barrel Length:");

		jLabel94.setText("Angle:");

		jLabel95.setText("mm");

		jLabel96.setText("mm");

		jLabel97.setText("mm");

		submitBarrel.setText("Submit Barrel");
		submitBarrel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				submitBarrelActionPerformed(evt);
			}
		});

		barrelDescription
				.setText("Creates a simple grip with a hole for items to slide into.");
		setBarrel(barrel);
		Panel.remove(finish);
		Panel.addTab("Barrel Settings", barrelSettings);
		Panel.setSelectedIndex(Panel.indexOfTab("Barrel Settings"));
	}

	private void finish() {
		jLabel77.setText("Select desired Files:");

		selectProfile.setText("Profile");

		selectSCAD.setText("OpenSCAD File");
		selectSCAD.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				selectSCADActionPerformed(evt);
			}
		});

		selectSTL.setText("STL File (for printing)");

		submitFinish.setText("Finish");
		submitFinish.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					submitFinishActionPerformed(evt);
				} catch (PositionNotSupportedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (invalidDiameterException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (invalidDimmensionsException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (STLNotPresentException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel78.setText("Once submitted all selected files wil appear in selected directory.");

		jLabel79.setText("Profile and STL files can be moved from this location.");

		jLabel80.setText("The OpenSCAD file requires files located in the selected directory, copy the directory if you wish to move this file.");

		gripName.setText("grip");

		jLabel81.setText("Grip Name:");

		lefty.setText("Left Handed Grip?");
		lefty.setSelected(gripFab.lefty);

		Panel.addTab("Finish", finish);
		Panel.setSelectedIndex(Panel.indexOfTab("Finish"));
	}

	private void setLayouts() {
		// directory
		javax.swing.GroupLayout directoryLayout = new javax.swing.GroupLayout(
				directory);
		directory.setLayout(directoryLayout);
		directoryLayout
				.setHorizontalGroup(directoryLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								directoryLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												directoryLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																directoryChooser,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																647,
																Short.MAX_VALUE)
														.addGroup(
																directoryLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel76)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		directoryLayout
				.setVerticalGroup(directoryLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								directoryLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel76)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												directoryChooser,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addContainerGap()));
		// grips
		javax.swing.GroupLayout gripsLayout = new javax.swing.GroupLayout(grips);
		grips.setLayout(gripsLayout);
		gripsLayout
				.setHorizontalGroup(gripsLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gripsLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												gripsLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																profileChooser,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																647,
																Short.MAX_VALUE)
														.addGroup(
																gripsLayout
																		.createSequentialGroup()
																		.addComponent(
																				newCheck)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				gripBox,
																				0,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addGroup(
																gripsLayout
																		.createSequentialGroup()
																		.addComponent(
																				profileCheck)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				chooseGrip))
														.addGroup(
																gripsLayout
																		.createSequentialGroup()
																		.addGap(24,
																				24,
																				24)
																		.addComponent(
																				jLabel29)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		gripsLayout
				.setVerticalGroup(gripsLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gripsLayout
										.createSequentialGroup()
										.addGap(12, 12, 12)
										.addGroup(
												gripsLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																gripBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(newCheck))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel29)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												gripsLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																chooseGrip,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																profileCheck))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												profileChooser,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												393, Short.MAX_VALUE)
										.addContainerGap()));
		// hole Settings
		javax.swing.GroupLayout holeSettingsLayout = new javax.swing.GroupLayout(
				holeSettings);
		holeSettings.setLayout(holeSettingsLayout);
		holeSettingsLayout
				.setHorizontalGroup(holeSettingsLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								holeSettingsLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												holeSettingsLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																holeSettingsLayout
																		.createSequentialGroup()
																		.addGap(10,
																				10,
																				10)
																		.addComponent(
																				holeChoices,
																				0,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addGroup(
																holeSettingsLayout
																		.createSequentialGroup()
																		.addGroup(
																				holeSettingsLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel74)
																						.addGroup(
																								holeSettingsLayout
																										.createSequentialGroup()
																										.addGroup(
																												holeSettingsLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																diameterLabel)
																														.addComponent(
																																jLabel85)
																														.addComponent(
																																jLabel86))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												holeSettingsLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel82)
																														.addComponent(
																																jLabel83)
																														.addComponent(
																																jLabel84)
																														.addGroup(
																																holeSettingsLayout
																																		.createSequentialGroup()
																																		.addGroup(
																																				holeSettingsLayout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING,
																																								false)
																																						.addComponent(
																																								diameterSlider,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								513,
																																								Short.MAX_VALUE)
																																						.addComponent(
																																								widthSlider,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE)
																																						.addComponent(
																																								heightSlider,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE))
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addGroup(
																																				holeSettingsLayout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addGroup(
																																								holeSettingsLayout
																																										.createSequentialGroup()
																																										.addGroup(
																																												holeSettingsLayout
																																														.createParallelGroup(
																																																javax.swing.GroupLayout.Alignment.LEADING)
																																														.addComponent(
																																																height,
																																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																																javax.swing.GroupLayout.PREFERRED_SIZE)
																																														.addComponent(
																																																width,
																																																javax.swing.GroupLayout.Alignment.TRAILING,
																																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																																javax.swing.GroupLayout.PREFERRED_SIZE))
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addGroup(
																																												holeSettingsLayout
																																														.createParallelGroup(
																																																javax.swing.GroupLayout.Alignment.LEADING)
																																														.addComponent(
																																																jLabel88)
																																														.addComponent(
																																																jLabel89)))
																																						.addGroup(
																																								holeSettingsLayout
																																										.createSequentialGroup()
																																										.addComponent(
																																												diameter,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												javax.swing.GroupLayout.DEFAULT_SIZE,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												jLabel87)))))))
																		.addGap(0,
																				23,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																holeSettingsLayout
																		.createSequentialGroup()
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				submitHole)))
										.addContainerGap())
						.addGroup(
								holeSettingsLayout
										.createSequentialGroup()
										.addGap(41, 41, 41)
										.addComponent(holeDescription)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		holeSettingsLayout
				.setVerticalGroup(holeSettingsLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								holeSettingsLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel74)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												holeChoices,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(holeDescription)
										.addGap(8, 8, 8)
										.addGroup(
												holeSettingsLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																diameterLabel)
														.addComponent(
																diameterSlider,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																holeSettingsLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				diameter,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel87)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel82)
										.addGap(18, 18, 18)
										.addGroup(
												holeSettingsLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																heightSlider,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel85)
														.addGroup(
																holeSettingsLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				height,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel88)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel83)
										.addGap(18, 18, 18)
										.addGroup(
												holeSettingsLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																widthSlider,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel86)
														.addGroup(
																holeSettingsLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				width,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel89)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel84)
										.addGap(18, 18, 18)
										.addComponent(submitHole)
										.addContainerGap(194, Short.MAX_VALUE)));
		// barrel Settings
		javax.swing.GroupLayout barrelSettingsLayout = new javax.swing.GroupLayout(
				barrelSettings);
		barrelSettings.setLayout(barrelSettingsLayout);
		barrelSettingsLayout
				.setHorizontalGroup(barrelSettingsLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								barrelSettingsLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												barrelSettingsLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																barrelSettingsLayout
																		.createSequentialGroup()
																		.addGroup(
																				barrelSettingsLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel900)
																						.addComponent(
																								jLabel93)
																						.addComponent(
																								jLabel94))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				barrelSettingsLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel90)
																						.addComponent(
																								jLabel91)
																						.addComponent(
																								jLabel92)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								barrelSettingsLayout
																										.createSequentialGroup()
																										.addGroup(
																												barrelSettingsLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addGroup(
																																barrelSettingsLayout
																																		.createSequentialGroup()
																																		.addGap(0,
																																				0,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				submitBarrel))
																														.addGroup(
																																barrelSettingsLayout
																																		.createSequentialGroup()
																																		.addGroup(
																																				barrelSettingsLayout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																						.addComponent(
																																								loutSlider,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE)
																																						.addGroup(
																																								barrelSettingsLayout
																																										.createSequentialGroup()
																																										.addGap(0,
																																												0,
																																												Short.MAX_VALUE)
																																										.addComponent(
																																												linSlider,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												492,
																																												javax.swing.GroupLayout.PREFERRED_SIZE))
																																						.addComponent(
																																								angleSlider,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE))
																																		.addGroup(
																																				barrelSettingsLayout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addGroup(
																																								barrelSettingsLayout
																																										.createSequentialGroup()
																																										.addGap(10,
																																												10,
																																												10)
																																										.addComponent(
																																												lin,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												javax.swing.GroupLayout.DEFAULT_SIZE,
																																												javax.swing.GroupLayout.PREFERRED_SIZE))
																																						.addGroup(
																																								barrelSettingsLayout
																																										.createSequentialGroup()
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addGroup(
																																												barrelSettingsLayout
																																														.createParallelGroup(
																																																javax.swing.GroupLayout.Alignment.LEADING)
																																														.addComponent(
																																																angle,
																																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																																javax.swing.GroupLayout.PREFERRED_SIZE)
																																														.addComponent(
																																																lout,
																																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																																javax.swing.GroupLayout.PREFERRED_SIZE))))
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addGroup(
																																				barrelSettingsLayout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addComponent(
																																								jLabel95)
																																						.addComponent(
																																								jLabel96)
																																						.addComponent(
																																								jLabel97))))
																										.addGap(19,
																												19,
																												19))))
														.addGroup(
																barrelSettingsLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel75)
																		.addContainerGap(
																				458,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																barrelSettingsLayout
																		.createSequentialGroup()
																		.addComponent(
																				barrelChoices,
																				0,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGap(19,
																				19,
																				19))))
						.addGroup(
								barrelSettingsLayout
										.createSequentialGroup()
										.addGap(41, 41, 41)
										.addComponent(barrelDescription)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		barrelSettingsLayout
				.setVerticalGroup(barrelSettingsLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								barrelSettingsLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel75)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												barrelChoices,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(8, 8, 8)
										.addComponent(barrelDescription)
										.addGroup(
												barrelSettingsLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																barrelSettingsLayout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				barrelSettingsLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								linSlider,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel900))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel90))
														.addGroup(
																barrelSettingsLayout
																		.createSequentialGroup()
																		.addGap(17,
																				17,
																				17)
																		.addGroup(
																				barrelSettingsLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								lin,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel95))))
										.addGap(18, 18, 18)
										.addGroup(
												barrelSettingsLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																barrelSettingsLayout
																		.createSequentialGroup()
																		.addGroup(
																				barrelSettingsLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								barrelSettingsLayout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel93)
																										.addGap(14,
																												14,
																												14)
																										.addComponent(
																												jLabel91)
																										.addGap(18,
																												18,
																												18))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								barrelSettingsLayout
																										.createSequentialGroup()
																										.addGroup(
																												barrelSettingsLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																lout,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																jLabel96))
																										.addGap(38,
																												38,
																												38)))
																		.addGroup(
																				barrelSettingsLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								angleSlider,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel94)
																						.addGroup(
																								barrelSettingsLayout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												angle,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jLabel97)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel92))
														.addComponent(
																loutSlider,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addComponent(submitBarrel)
										.addContainerGap(197, Short.MAX_VALUE)));
		// finish
		javax.swing.GroupLayout finishLayout = new javax.swing.GroupLayout(
				finish);
		finish.setLayout(finishLayout);
		finishLayout
				.setHorizontalGroup(finishLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								finishLayout
										.createSequentialGroup()
										.addGroup(
												finishLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																finishLayout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				finishLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								finishLayout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel81)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												gripName))
																						.addComponent(
																								lefty)
																						.addGroup(
																								finishLayout
																										.createSequentialGroup()
																										.addGap(10,
																												10,
																												10)
																										.addGroup(
																												finishLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																selectProfile)
																														.addComponent(
																																jLabel78)
																														.addComponent(
																																jLabel79)
																														.addComponent(
																																jLabel80)
																														.addComponent(
																																selectSCAD)))
																						.addComponent(
																								submitFinish,
																								javax.swing.GroupLayout.Alignment.TRAILING)))
														.addGroup(
																finishLayout
																		.createSequentialGroup()
																		.addGap(46,
																				46,
																				46)
																		.addComponent(
																				selectSTL))
														.addGroup(
																finishLayout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel77)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		finishLayout
				.setVerticalGroup(finishLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								finishLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												finishLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel81)
														.addComponent(
																gripName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(lefty)
										.addGap(21, 21, 21)
										.addComponent(jLabel77)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(selectProfile)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												selectSCAD,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												25,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(selectSTL)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(submitFinish)
										.addGap(6, 6, 6)
										.addComponent(jLabel78)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel79).addGap(2, 2, 2)
										.addComponent(jLabel80)
										.addContainerGap(234, Short.MAX_VALUE)));
	}

	// Variables declaration - do not modify
	private javax.swing.JTabbedPane Panel;
	private javax.swing.JTextField angle;
	private javax.swing.JSlider angleSlider;
	private javax.swing.JComboBox<?> barrelChoices;
	private javax.swing.JLabel barrelDescription;
	private javax.swing.JPanel barrelSettings;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton chooseGrip;
	private javax.swing.JTextField diameter;
	private javax.swing.JLabel diameterLabel;
	private javax.swing.JSlider diameterSlider;
	private javax.swing.JPanel directory;
	private javax.swing.JFileChooser directoryChooser;
	private javax.swing.JPanel finish;
	private javax.swing.JComboBox<?> gripBox;
	private javax.swing.JTextField gripName;
	private javax.swing.JPanel grips;
	private javax.swing.JTextField height;
	private javax.swing.JSlider heightSlider;
	private javax.swing.JComboBox<?> holeChoices;
	private javax.swing.JLabel holeDescription;
	private javax.swing.JPanel holeSettings;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel jLabel74;
	private javax.swing.JLabel jLabel75;
	private javax.swing.JLabel jLabel76;
	private javax.swing.JLabel jLabel77;
	private javax.swing.JLabel jLabel78;
	private javax.swing.JLabel jLabel79;
	private javax.swing.JLabel jLabel80;
	private javax.swing.JLabel jLabel81;
	private javax.swing.JLabel jLabel82;
	private javax.swing.JLabel jLabel83;
	private javax.swing.JLabel jLabel84;
	private javax.swing.JLabel jLabel85;
	private javax.swing.JLabel jLabel86;
	private javax.swing.JLabel jLabel87;
	private javax.swing.JLabel jLabel88;
	private javax.swing.JLabel jLabel89;
	private javax.swing.JLabel jLabel90;
	private javax.swing.JLabel jLabel900;
	private javax.swing.JLabel jLabel91;
	private javax.swing.JLabel jLabel92;
	private javax.swing.JLabel jLabel93;
	private javax.swing.JLabel jLabel94;
	private javax.swing.JLabel jLabel95;
	private javax.swing.JLabel jLabel96;
	private javax.swing.JLabel jLabel97;
	private javax.swing.JCheckBox lefty;
	private javax.swing.JTextField lin;
	private javax.swing.JSlider linSlider;
	private javax.swing.JTextField lout;
	private javax.swing.JSlider loutSlider;
	private javax.swing.JRadioButton newCheck;
	private javax.swing.JRadioButton profileCheck;
	private javax.swing.JFileChooser profileChooser;
	private javax.swing.JCheckBox selectProfile;
	private javax.swing.JCheckBox selectSCAD;
	private javax.swing.JCheckBox selectSTL;
	private javax.swing.JButton submitBarrel;
	private javax.swing.JButton submitFinish;
	private javax.swing.JButton submitHole;
	private javax.swing.JTextField width;
	private javax.swing.JSlider widthSlider;
	// End of variables declaration
}
